version: "3.8"
services:
  web:
    image: python:3.9-alpine
    command: sh -c "pip install -r /app/requirements.txt && python -m flask run --host=0.0.0.0"
    tty: true
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    environment:
      FLASK_APP: application.py
    ports:
      - "8000:5000"
